### ISSUE TITLE
mark 14.1 broken and push a new build of 14 instead

### ISSUE THREAD

**Issue by beckermr** [conda-forge/vc-feedstock#13]
Per discussion with @isuruf we've decided to not bump to 14.1 and use a new build of 14 instead.

**Comment by jakirkham** [comment]
Where was this discussion?

**Comment by beckermr** [comment]
On Gitter. It went fast. Basically we have a lot of recipes with a selector that is “vc < 14” which breaks with 14.1

**Comment by beckermr** [comment]
We will actually ship 14.1 but call it 14

**Comment by jakirkham** [comment]
It would be useful to have a link. Just helps for keeping everyone in the loop 🙂

**Comment by beckermr** [comment]
Sorry yeah. I might also be confused on this. Maybe we don't bump to 14.1 in the pinnings but still ship 14.1 here.

**Comment by isuruf** [comment]
`14.1` is part of `14` (and so is `14.0`), so no need to mark as broken.
