### ISSUE TITLE
uploading of new builds fail

### ISSUE THREAD

**Issue by isuruf** [conda-forge/vc-feedstock#25]
cc @beckermr

**Comment by beckermr** [comment]
I will need more info to help debug.

**Comment by isuruf** [comment]
Packages don't seem to upload. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=275338&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=5c98bdd2-7d13-5885-fcfb-2c6e579b24c3

**Comment by beckermr** [comment]
This is presumably a bug in the ci support package. I'd suggest we move this convo there.

**Comment by beckermr** [comment]
Lots of other feedstocks are uploading to cf-staging FWIW. 

https://anaconda.org/cf-staging/repo/history

**Comment by beckermr** [comment]
And they are doing copies too. hmmmmm....

**Comment by beckermr** [comment]
Did this resolve itself?

**Comment by isuruf** [comment]
Nope. A rerendering didn't help either

**Comment by beckermr** [comment]
Ok. This is def a bug in the ci support package. It must not be computing that there are any artifacts to upload. It will have to be debugged manually

**Comment by isuruf** [comment]
cc @conda-forge/core. This is blocking fixing a serious issue in this feedstock which is used by all conda-forge packages on windows. I might build the recipe on the server and upload manually.

**Comment by beckermr** [comment]
I will look this afternoon. Sorry for the delay. I won't be able to debug this on windows so my plan is to try it in the CI with a copy of the ci support package and print out what is going wrong.

**Comment by beckermr** [comment]
@isuruf The build number bump in your PR failed because you bumped the top-level one but none of them in the outputs.

**Comment by beckermr** [comment]
closing!
