### ISSUE TITLE
vs2019 compiler activation failure with Visual Studio 2019 16.10

### ISSUE THREAD

**Issue by ryanvolz** [conda-forge/vc-feedstock#36]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I'm trying out a Windows build with vs2019 on one of my feedstocks, and it is failing in the activation script with
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>CALL "VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.28 10.0.19041.0 
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.10.0
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[ERROR:vcvars.bat] Toolset directory for version '14.28' was not found.
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
        1 file(s) copied.
```
The full log is [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=335164&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f). I tested locally and can confirm that the activation works with VS 2019 version 16.9 but now fails with version 16.10. The latest Azure images have unfortunately upgraded to 16.10, so I expect all new builds with vs2019 will fail.

**Comment by Tobias-Fischer** [comment]
Can confirm that this is causing issues in https://github.com/conda-forge/libignition-physics-feedstock/pull/16

**Comment by izahn** [comment]
Yep, we have the same in https://github.com/conda-forge/leptonica-feedstock/pull/31

**Comment by traversaro** [comment]
I investigated a bit, and it seems that differently from Visual Studio 2017 the `vcvars_ver` the major.minor version is not fixed for a the minor versions of Visual Studio 2019:
https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#vcvarsall-syntax

In my system I removed completly the `-vcvars_ver=<maj.min>` argument passed to `vcvars` invocation, and this works fine, but I do not know what is the rationale with with it was introduced in the first place that argument.

A possible alternative (not in CI) is to explicitly install the 14.28 toolset (see https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2019/):
![14_28](https://user-images.githubusercontent.com/1857049/121931798-5efc5f00-cd44-11eb-80fd-0b0d8371086b.PNG)

**Comment by andfoy** [comment]
This is also affecting https://github.com/conda-forge/pywinpty-feedstock/pull/35

**Comment by isuruf** [comment]
PRs welcome to update this feedstock from 16.9 to 16.10

**Comment by traversaro** [comment]
> PRs welcome to update this feedstock from 16.9 to 16.10

Just to understand, breaking 16.9 compatibility is considered ok? To you have any pointer on why just removing `-vcvars_ver=<maj.min>` is a problematic change?

**Comment by isuruf** [comment]
> Just to understand, breaking 16.9 compatibility is considered ok?

I don't understand this question.

> To you have any pointer on why just removing -vcvars_ver=<maj.min> is a problematic change?

We only ship the VS runtime DLLs from 16.9 for now and if we remove `-vcvars_ver=<maj.min>`, then the compiler will use symbols from 16.10

**Comment by traversaro** [comment]
> > Just to understand, breaking 16.9 compatibility is considered ok?
> 
> I don't understand this question.

If somebody has a Visual Studio 16.9 installation, updating the script would break the execution of `vcvars64.bat` on their machine, as they don't have a 16.10 installed on their machine. However, from the following answer I guess that people with VS 16.9 are expected to install the corresponding version of `vs2019_win-64` package.

> > To you have any pointer on why just removing -vcvars_ver=<maj.min> is a problematic change?
> 
> We only ship the VS runtime DLLs from 16.9 for now and if we remove `-vcvars_ver=<maj.min>`, then the compiler will use symbols from 16.10

I see, thanks!

**Comment by isuruf** [comment]
>  However, from the following answer I guess that people with VS 16.9 are expected to install the corresponding version of vs2019_win-64 package.

Yes, they can set 
```
c_compiler_version: # [win]
  - 19.28                    # [win]
```
in their `<HOME>/conda_build_config.yaml`

**Comment by ryanvolz** [comment]
Thanks for the fix @traversaro and @isuruf!
