### ISSUE TITLE
VS2022 released

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/vc-feedstock#39]
Probably will be some time before this becomes relevant, but here's the [announcement](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-now-available/). Looks like the build is already templated enough that this shouldn't be too hard to add.

**Comment by h-vetinari** [comment]
@conda-forge/vc 
It would be pretty cool to have the most current VS version also available in conda-forge, if only to verify that certain things are compiler bugs (e.g. by testing vs2022 and finding things pass). Currently neck-deep in static initialization mess with MSVC + protobuf, and would like to rule out that it's "just" the MSVC version...

**Comment by traversaro** [comment]
Not a replacement to have a `vs2022_win-64` package, but if you just need to compile a project with VS2022 for a test, a quick solution is to use the generator `Visual Studio 17 2022`, i.e. something like:
~~~
cmake -G"Visual Studio 17 2022" ..
cmake --build . --config Release 
cmake --install . --config Release
~~~

The main advantage of `Visual Studio 17 2022` or similar generator is that they work fine in any command prompt, even if the related developer scripts have not been sourced.

**Comment by h-vetinari** [comment]
So nominally this was closed by https://github.com/conda-forge/vc-feedstock/pull/46, but it appears there are still some rough edges.

In https://github.com/conda-forge/prismatic_split-feedstock/pull/34, the main compiler CLI isn't being found:
```
CMake Error at D:/bld/prismatic_split_1672827794149/_build_env/Library/share/cmake-3.25/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  cl.exe.
```

**Comment by wolfv** [comment]
@h-vetinari that's not the source of the issue. it's earlier, and looks like the same problem (vsvars64.bat doesn't properly run because the version doesn't match).

**Comment by wolfv** [comment]
I've used VC 2022 now, and it seems to work :) should we close this one?
