### ISSUE TITLE
Fix CMAKE_GENERATOR when Visual Studio 2019 is used for vc141

### ISSUE THREAD

**Issue by isuruf** [conda-forge/vc-feedstock#41]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

cc @henryiii

**Comment by henryiii** [comment]
Do you know what is broken? pybind11 doesn't even compile anything but is unable to update due to this issue. Is there a workaround?

**Comment by wshanks** [comment]
@henryiii In my case (https://github.com/conda-forge/gdstk-feedstock/pull/20), reverting the `windowsVM` back to `vs2017-win2016` in ` .azure-pipelines/azure-pipelines-win.yml` allowed the build to succeed, though I assume this is not a viable long term solution.
