### ISSUE TITLE
Problems with VS2022 activation in Azure CI with version 14.37

### ISSUE THREAD

**Issue by TonyXiang8787** [conda-forge/vc-feedstock#67]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The MSVC version in Azure CI has been upgraded to `14.37`. We get now errors when `vs2022` tries to activate version `14.36` which does not exist anymore in de Azure CI image. See this [build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=776497&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0bf03e01-0bec-5b85-5316-b1633322e895&l=442).

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[ERROR:vcvars.bat] Toolset directory for version '14.36' was not found.
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
```

Similar problem has occurred in #63 and has been fixed in #64.

### Installed packages

```shell
not applicable
```

### Environment info

```shell
Windows Build in Azure CI using VS2022
```

**Comment by TonyXiang8787** [comment]
@h-vetinari could you please have a look. I tried to contribute a PR here, but I have no idea how to get the new `sha256` and `uuid` field in `conda_build_config.yaml`.

**Comment by jaimergp** [comment]
cc @conda-forge/vc for visibility / awareness.

**Comment by isuruf** [comment]
> I have no idea how to get the new sha256 and uuid field in conda_build_config.yaml.

See https://github.com/conda-forge/vc-feedstock/blob/97ada02cef22b60a8d64c71c16f58297046bf24a/recipe/conda_build_config.yaml#L37-L39

**Comment by mjcarroll** [comment]
A note that the `aka.ms` link still returns the `14.36.32532` installer for me and has the same `uuid` in the URL.

It may be an earlier candidate on Azure before the rest of the community gets it?

**Comment by h-vetinari** [comment]
Thanks for the report. Previously, MSFT only used the "LTS" versions in the images, which happened to be the even releases for the last couple of updates.

If the images are indeed on 19.37 now, we'll have to upgrade. I guess we're not seeing this widely because it only affects vs2022, which your feedstock is [using](https://github.com/conda-forge/power-grid-model-feedstock/blob/main/recipe/conda_build_config.yaml), but not the default in conda-forge. Unless you're using very recent C++ features, you should also be fine with downgrading that to vs2019?

If not, could you open a PR along the lines of adab9a3775feacfb0a1e07f6f3e2fe12f724120d & f54ce138ed4abf9b7d0aa8a98e81a0efe6f8a2b6?

**Comment by TonyXiang8787** [comment]
> A note that the `aka.ms` link still returns the `14.36.32532` installer for me and has the same `uuid` in the URL.
> 
> It may be an earlier candidate on Azure before the rest of the community gets it?

Hi @mjcarroll, in the Azure image (and also in my local laptop) is the version of MSVC runtime still at `14.36.32532`. The `cl` compiler version has been upgraded to `19.37.32822` and the toolchain version is `14.37.32822`, which is needed in the command call of `vcvars64.bat -vcvars_ver=`.



> Thanks for the report. Previously, MSFT only used the "LTS" versions in the images, which happened to be the even releases for the last couple of updates.
> 
> If the images are indeed on 19.37 now, we'll have to upgrade. I guess we're not seeing this widely because it only affects vs2022, which your feedstock is [using](https://github.com/conda-forge/power-grid-model-feedstock/blob/main/recipe/conda_build_config.yaml), but not the default in conda-forge. Unless you're using very recent C++ features, you should also be fine with downgrading that to vs2019?
> 
> If not, could you open a PR along the lines of [adab9a3](https://github.com/conda-forge/vc-feedstock/commit/adab9a3775feacfb0a1e07f6f3e2fe12f724120d) & [f54ce13](https://github.com/conda-forge/vc-feedstock/commit/f54ce138ed4abf9b7d0aa8a98e81a0efe6f8a2b6)?

Hi @h-vetinari, indeed we use the latest C++ features. Therefore we need `vs2022` in the pipeline. I will make a PR.
